# To get started with Dependabot version updates, you'll need to specify which
# package#Pour commencer les mises à jour de version de Dependabot, vous devrez spécifier laquelle
#Écosystèmes de paquets à mettre à jour et emplacement des manifestes des paquets.
#Veuillez consulter la documentation pour connaître toutes les options de configuration :
#https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
 ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
